spring:
  application:
    name: gerenciador_gasto
  datasource:
    url: jdbc:mysql://localhost:3307/gerenciador_gasto
    username: root
    password: tos200689
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  threads:
    virtual:
      enabled: true

server:
  error:
    include-stacktrace: on-param

logging:
  level:
    org.springframework.security: debug

jwt:
  secret: TAYLORMEINHAMOEDINHAAPP1234567890